### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by brightghost** [yconst/Hoopsnake#1]
Hello,

I  understand this project is not in active development. The repo here lists a CC BY-SA license for this project, but the project website lists the license as CC BY-NC-ND 3.0. Which is it? I need to know if it use by commercial architecture firms is permitted.

**Comment by yconst** [comment]
Hi,

It's CC-BY-SA. The website is outdated, I'll update when there is some time. You may use it in your firm's projects; appropriate citation would be very much appreciated.
